---
- name: Terminate specific AWS EC2 instance
  hosts: localhost
  vars_files:
    - secret.yaml
  become: false
  gather_facts: false

  tasks:
    - name: Fetch instances with specific tag
      amazon.aws.ec2_instance_info:
        region: us-east-1
        aws_access_key: "{{ aws_access_key1 }}"
        aws_secret_key: "{{ aws_secret_key1 }}"
        filters:
          "tag:Environment": "Linux_test"  # Replace with your tag key and value
      register: ec2_info

    - name: Debug fetched instances
      debug:
        var: ec2_info

    - name: Terminate the EC2 instance
      amazon.aws.ec2_instance:
        region: us-east-1
        aws_access_key: "{{ aws_access_key1 }}"
        aws_secret_key: "{{ aws_secret_key1 }}"
        instance_ids: "{{ item.instance_id }}"
        state: absent
      loop: "{{ ec2_info.instances }}"
      register: terminated_instance

    - name: Debug termination result
      debug:
        var: terminated_instance
