---
- hosts: all
  become: yes
  tasks:
    - name: Install apache httpd
      ansible.builtin.apt:
        name: apache2
        state: present
    - name: Copy a new "ntp.conf" file into place, backing up the original if it differs from the copied version
      ansible.builtin.copy:
        src: index.html
        dest: /var/www/html
        owner: root
        group: root
        mode: '0644'
        backup: yes
